import type { ReactNode } from 'react'

const team = [
  ['Franz Salazar', 'Leader / Programmer', 'FS'], ['Jhon Roy Gamboa', 'Tester / QA', 'JG'], ['Matthew', 'Automata Optimizer', 'MA'],
  ['Ace Sandoval', 'DFA Designer', 'AS'], ['Bench Culubong', 'Language Analyst', 'BC'], ['Jude Prodi', 'RE / NFA Designer', 'JP'],
  ['James Berto', 'RE / NFA Designer', 'JB'], ['Alecks Santos', 'Programmer', 'AS'], ['Leona Charlize', 'Documentation', 'LC'],
]
const rows = [['keyword','let','KEYWORD','1','1'],['identifier','total','IDENTIFIER','1','5'],['operator','=','OPERATOR','1','11'],['number','42','NUMBER','1','13'],['punctuation',';','PUNCTUATION','1','15'],['identifier','print','IDENTIFIER','2','1'],['string','"hello"','STRING','2','7']]
const dotKinds = ['keyword','identifier','operator','number','punctuation','string']

function Dot({ kind }: { kind: string }) { return <i className={`dot dot-${kind}`} /> }
function Logo() { return <div className="o-logo"><b>L</b><span>LexiScan</span></div> }
function Glass({ children, className = '' }: { children: ReactNode; className?: string }) { return <div className={`o-glass ${className}`}>{children}</div> }
function Frame({ name, className = '', children }: { name: string; className?: string; children: ReactNode }) { return <article className={`frame-wrap ${className}`}><h2 className="canvas-label">{name}</h2><div className="frame" aria-label={name}>{children}</div></article> }
function Section({ name, children }: { name: string; children: ReactNode }) { return <section className="overview-section"><div className="section-name">{name}</div><div className="frame-row">{children}</div></section> }
function Button({ children, ghost = false, loading = false }: { children: ReactNode; ghost?: boolean; loading?: boolean }) { return <button className={`o-button ${ghost ? 'ghost' : ''} ${loading ? 'loading' : ''}`}>{loading && <i className="spinner" />}{children}</button> }
function TeamGrid() { return <div className="team-grid">{team.map(([name, role, initials], index) => <div className="team-item" key={name}><span className="avatar">{initials}</span><div><b>{name}{index === 0 && <em>LEAD</em>}</b><small>{role}</small></div></div>)}</div> }
function Code({ error = false, empty = false }: { error?: boolean; empty?: boolean }) { return <div className={`code-block ${empty ? 'empty-code' : ''}`}>{empty ? <span>Paste or type source code here…</span> : <><div><i>1</i><code><em>let</em> total <b>=</b> <strong>42</strong>;</code></div><div><i>2</i><code>print(<u>"hello"</u>);</code></div>{error && <div><i>3</i><code>total <b>=</b> <mark>@</mark>;</code></div>}</>}</div> }
function TokenTable({ count = '24 tokens', selected = 1, compact = false }: { count?: string; selected?: number; compact?: boolean }) { const shown = compact ? rows.slice(0, 4) : rows; return <div className="tokens"><div className="token-toolbar"><label>⌕ <input placeholder="Filter tokens" defaultValue={count === '24 tokens' ? '': 'total'} /></label><span>{count}</span></div><div className="token-head"><span>Token</span><span>Lexeme</span><span>Type</span><span>Line</span><span>Col</span></div>{shown.map((r, index) => <div className={`token-row ${selected === index ? 'selected' : ''}`} key={`${r[1]}-${index}`}><span><Dot kind={r[0]} />{r[0]}</span><code>{r[1]}</code><code>{r[2]}</code><span>{r[3]}</span><span>{r[4]}</span></div>)}</div> }
function AppShell({ state }: { state: 'empty'|'default'|'scanning'|'complete'|'error' }) { const isError = state === 'error'; const isScan = state === 'scanning'; const isEmpty = state === 'empty'; return <div className="app-frame"><header className="app-nav"><Logo /><div className="app-file">● untitled.lex⌄</div><Button loading={isScan}>{isScan ? 'Scanning…' : '▶ Run Analysis'}</Button><button className="settings">⚙</button></header><div className="app-workspace"><Glass className="app-panel"><div className="panel-title"><div><small>EDITOR</small><b>Source Input</b></div><span>JavaScript</span></div><div className="hairline"/><Code empty={isEmpty} error={isError}/><div className="panel-bottom">UTF-8 <span>Ln 1, Col 1</span></div></Glass><Glass className="app-panel"><div className="panel-title"><div><small>RESULTS</small><b>Token Output</b></div><span>{isEmpty ? 'No results' : isScan ? 'Scanning' : '24 tokens'}</span></div><div className="hairline"/>{isError ? <div className="error-area"><div className="error-banner">LexerError: unrecognized character '@' — line 3, col 7</div><p>Fix the marked character and run analysis again.</p></div> : isEmpty ? <div className="empty-state"><i>⌁</i><b>Run analysis to see tokens.</b><span>Your parsed lexemes will appear here.</span></div> : isScan ? <div className="scan-area"><span>scanning…</span><div className="skeleton"/><div className="skeleton"/><div className="skeleton short"/><div className="skeleton"/></div> : <TokenTable count={state === 'complete' ? '7 shown' : '24 tokens'} selected={state === 'default' ? 1 : 5}/>}<div className="panel-bottom">{isError ? '1 error · 0 warnings' : isScan ? 'Analyzing source' : isEmpty ? 'Waiting for source' : 'Analysis complete'}<span>{isError ? 'Lexer halted' : '0 errors · 0 warnings'}</span></div></Glass></div><footer className="app-status"><span>● {isError ? '1 error · 0 warnings' : isScan ? 'Scanning…' : isEmpty ? 'Ready' : 'Analysis complete'}</span><span>LexiScan v0.8.4 · Local workspace</span></footer></div> }
function Landing() { return <div className="landing-frame"><nav><Logo /><div><a>Product</a><a>Token Reference</a><a>Team</a><a>Docs</a></div><Button>Open LexiScan →</Button></nav><section className="landing-hero"><p>LEXICAL ANALYZER · v0.8.4</p><h1>See every token in your source.</h1><h2>Paste code, get a clean, inspectable token stream.</h2><Button>Run the analyzer →</Button><Button ghost>View token reference</Button><Glass className="landing-demo"><div className="demo-bar">● ● ● <span>LexiScan — untitled.lex</span></div><div className="demo-grid"><div><b>Source Input</b><Code/></div><div><b>Token Output</b><TokenTable compact/></div></div></Glass></section><section className="landing-what"><p>WHAT IS A LEXICAL ANALYZER</p><div><article><h2>A scanner that reads code character by character.</h2><span>A lexical analyzer, or scanner, reads raw source code as a stream of characters and groups them into meaningful tokens — keywords, identifiers, operators, literals — so a parser can understand the program.</span></article><Glass><div className="bracket-code"><span className="keyword-token">let<small>KEYWORD</small></span><span className="identifier-token">total<small>IDENTIFIER</small></span><span className="operator-token">=<small>OPERATOR</small></span><span className="number-token">42<small>NUMBER</small></span><span className="punctuation-token">;<small>PUNCTUATION</small></span></div></Glass></div></section><section className="landing-steps"><p>HOW IT WORKS</p>{[['01','Paste source','Drop in code or a .lex file.'],['02','Scan','The analyzer splits input into tokens.'],['03','Inspect','Filter, select, and read token metadata.']].map(s=><article key={s[0]}><i>{s[0]}</i><b>{s[1]}</b><span>{s[2]}</span></article>)}</section><section className="landing-reference"><p>TOKEN REFERENCE</p><Glass><code><Dot kind="keyword"/> let total = 42; print("hello");</code><hr/><div>{dotKinds.map(k=><span key={k}><Dot kind={k}/>{k}</span>)}</div></Glass></section><section className="landing-team"><p>MEET THE TEAM</p><h2>The team behind LexiScan.</h2><TeamGrid/></section><Glass className="landing-cta"><p>READY WHEN YOU ARE</p><h2>Start scanning in seconds.</h2><span>No setup screen. Just paste your source and inspect what the language sees.</span><Button>Open LexiScan →</Button><small>No install · Runs locally · v0.8.4</small></Glass><footer><Logo/><span>Docs　GitHub　Changelog</span><code>LexiScan v0.8.4 · Local workspace</code></footer></div> }
function Branding() { const colors = [['Background','#F3F4F5'],['Ink','#22282C'],['Muted','#7C868D'],['Accent','#14586B']]; return <div className="brand-frame"><Logo/><p>LEXISCAN DESIGN SYSTEM · v0.8.4</p><div className="brand-grid"><article><h3>Color</h3>{colors.map(c=><div className="swatch" key={c[0]}><i style={{background:c[1]}}/><span>{c[0]}<code>{c[1]}</code></span></div>)}</article><article><h3>Typography</h3><b className="type-xl">Source, inspected.</b><b className="type-md">Interface title</b><code>MONOSPACE · MICRO LABEL</code></article><article><h3>Token palette</h3>{dotKinds.map(k=><span className="palette" key={k}><Dot kind={k}/>{k}</span>)}</article><article><h3>Surface</h3><Glass className="spec-glass">Glass / 14px radius</Glass><code>SHADOW<br/>0 2px 8px / 6%<br/>0 24px 60px / 8%</code></article></div></div> }
function TokenReference() { return <div className="info-frame"><header><Logo/><span>Token Reference</span><Button>Open LexiScan →</Button></header><main><p>TOKEN REFERENCE</p><h1>A compact vocabulary for your source.</h1><Glass><div className="reference-head"><span>Token type</span><span>Definition</span><span>Example</span></div>{[['keyword','KEYWORD','Reserved language word','let'],['identifier','IDENTIFIER','A named value or callable','total'],['operator','OPERATOR','An operation or assignment symbol','='],['number','NUMBER','Numeric literal','42'],['string','STRING','Quoted character sequence','"hello"'],['punctuation','PUNCTUATION','Structural source character',';'],['punctuation','DELIMITER','Separates grouped expressions',',']].map(r=><div className="reference-row" key={r[1]}><span><Dot kind={r[0]}/><code>{r[1]}</code></span><span>{r[2]}</span><code>{r[3]}</code></div>)}</Glass></main><footer>LexiScan v0.8.4 · Local workspace</footer></div> }
function HowWorks() { const bits=[['01 · SOURCE','Paste source','let total = 42;'],['02 · SCAN','Scan','let | total | = | 42 | ;'],['03 · OUTPUT','Inspect','identifier · total · line 1']]; return <div className="how-frame"><header><Logo/><Button>Open LexiScan →</Button></header><main><p>HOW IT WORKS</p><h1>From raw text to useful structure.</h1>{bits.map((b,i)=><section className="how-step" key={b[0]}><div><code>{b[0]}</code><h2>{b[1]}</h2><p>{i===0?'Drop in code or a .lex file.':i===1?'The analyzer reads one character at a time and groups meaningful sequences.':'Filter, select, and read the metadata behind every token.'}</p></div><Glass><code>{b[2]}</code></Glass></section>)}</main></div> }
function About() { return <div className="about-frame"><header><Logo/><Button>Open LexiScan →</Button></header><main><p>ABOUT LEXISCAN</p><h1>A lexical analyzer, made legible.</h1><article>LexiScan is a course project focused on building a lexical analyzer: a practical view into how a language tool reads source, identifies token boundaries, and prepares programs for parsing.</article><p>MEET THE TEAM</p><h2>The team behind LexiScan.</h2><TeamGrid/></main><footer>LexiScan v0.8.4 · Local workspace</footer></div> }

export default function App() { return <main className="overview-canvas"><h1>Overview</h1><Section name="Brand & Marketing"><Frame name="Branding Elements"><Branding/></Frame><Frame name="Home — Landing" className="tall-frame"><Landing/></Frame></Section><Section name="App States"><Frame name="Analyzer — Empty"><AppShell state="empty"/></Frame><Frame name="Analyzer — Default"><AppShell state="default"/></Frame><Frame name="Analyzer — Scanning"><AppShell state="scanning"/></Frame><Frame name="Analyzer — Complete"><AppShell state="complete"/></Frame><Frame name="Analyzer — Error"><AppShell state="error"/></Frame></Section><Section name="Info Pages"><Frame name="Token Reference" className="info-size"><TokenReference/></Frame><Frame name="How It Works" className="how-size"><HowWorks/></Frame><Frame name="About — Meet the Team" className="how-size"><About/></Frame></Section></main> }